#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"
import { generateDistNotice } from "./generate-notice"

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

// Generate full distribution NOTICE (static header + all dep license texts)
const repoRoot = path.resolve(dir, "../..")
const { notice: distNotice, deps: depList } = await generateDistNotice(
  path.join(repoRoot, "NOTICE"),
  dir,
)
console.log(`Generated distribution NOTICE (${depList.length} deps)`)

// Write dependency manifest for compliance tracking
await $`mkdir -p dist`
await Bun.write(
  path.join(dir, "dist/dependency-licenses.json"),
  JSON.stringify(depList, null, 2),
)
console.log("Written dist/dependency-licenses.json")

// Build the elastic CLI for each target platform (skip if directory doesn't exist)
const elasticCliDir = process.env.ELASTIC_CLI_DIR || path.resolve(dir, "../../../cli")
const buildElasticCli = fs.existsSync(elasticCliDir)
const goTargetMap: Record<string, { goos: string; goarch: string }> = {
  darwin: { goos: "darwin", goarch: "" },
  linux: { goos: "linux", goarch: "" },
  win32: { goos: "windows", goarch: "" },
}
const goArchMap: Record<string, string> = {
  arm64: "arm64",
  x64: "amd64",
}

if (buildElasticCli) {
  const seen = new Set<string>()
  for (const item of targets) {
    const goos = goTargetMap[item.os]?.goos ?? item.os
    const goarch = goArchMap[item.arch] ?? item.arch
    const key = `${goos}-${goarch}`
    if (seen.has(key)) continue
    seen.add(key)
    const ext = goos === "windows" ? ".exe" : ""
    const out = path.resolve(dir, `dist/elastic-cli/${key}/elastic${ext}`)
    await $`mkdir -p ${path.dirname(out)}`
    console.log(`building elastic CLI for ${key}`)
    await $`CGO_ENABLED=0 GOOS=${goos} GOARCH=${goarch} go build -trimpath -ldflags="-s -w" -o ${out} ./cmd/elastic`.cwd(
      elasticCliDir,
    )
  }
} else {
  console.log(`Skipping elastic CLI build (directory not found: ${elasticCliDir})`)
}

// Read all SKILL.md files to embed as a define constant
const skillsDir = path.resolve(dir, "src/elastic/skills")
const embeddedSkills: Record<string, string> = {}
if (fs.existsSync(skillsDir)) {
  for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const md = path.join(skillsDir, entry.name, "SKILL.md")
    if (fs.existsSync(md)) embeddedSkills[entry.name] = fs.readFileSync(md, "utf8")
  }
  console.log(`Embedded ${Object.keys(embeddedSkills).length} skills`)
}

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
// Derive a filesystem-safe base name from the (potentially scoped) package name.
// e.g. "@elastic/ramen" → "elastic-ramen"
const pkgBaseName = pkg.name.startsWith("@")
  ? pkg.name.slice(1).replace("/", "-")
  : pkg.name

for (const item of targets) {
  const name = [
    pkgBaseName,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  // Read the Go CLI binary for this target and embed as base64
  const goos = goTargetMap[item.os]?.goos ?? item.os
  const goarch = goArchMap[item.arch] ?? item.arch
  const ext = goos === "windows" ? ".exe" : ""
  const elasticBinPath = path.resolve(dir, `dist/elastic-cli/${goos}-${goarch}/elastic${ext}`)
  const elasticBinB64 = fs.existsSync(elasticBinPath)
    ? fs.readFileSync(elasticBinPath).toString("base64")
    : ""
  if (elasticBinB64) {
    console.log(`  embedding elastic CLI (${(elasticBinB64.length / 1024 / 1024 * 0.75).toFixed(1)} MB)`)
  }

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkgBaseName, "bun") as any,
      outfile: `dist/${name}/bin/elastic-ramen`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      ELASTIC_CLI_B64: JSON.stringify(elasticBinB64),
      ELASTIC_SKILLS_EMBEDDED: JSON.stringify(embeddedSkills),
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`

  // npm package name: scoped if the main package is scoped (e.g. @elastic/ramen-darwin-arm64)
  const scope = pkg.name.startsWith("@") ? pkg.name.split("/")[0] + "/" : ""
  const npmName = scope + name

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name: npmName,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[npmName] = Script.version
}

if (Script.release) {
  // Write legal files into each platform bin dir so they are included in the archive.
  // NOTICE is the fully-generated version (static header + all dep license texts).
  const licensePath = path.join(repoRoot, "LICENSE")

  for (const key of Object.keys(binaries)) {
    const binDir = path.join(dir, `dist/${key}/bin`)
    await Bun.write(path.join(binDir, "NOTICE"), distNotice)
    if (fs.existsSync(licensePath)) {
      fs.copyFileSync(licensePath, path.join(binDir, "LICENSE"))
    }
    const bin =
      ["elastic-ramen", "elastic-ramen.exe"].find((file) => fs.existsSync(path.join(binDir, file))) ??
      (key.includes("windows") ? "elastic-ramen.exe" : "elastic-ramen")
    const files = [bin, "NOTICE"]
    if (fs.existsSync(path.join(binDir, "LICENSE"))) {
      files.push("LICENSE")
    }
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz ${files}`.cwd(binDir)
    } else {
      await $`zip -r ../../${key}.zip ${files}`.cwd(binDir)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
